name: "Should publish package"
description: "Check if a package with a given version should be published"
inputs:
  repository-url:
    description: "The URL of the repository to check"
    required: true
  repository-login:
    description: "The login to use to authenticate to the NPM repository"
    required: true
  repository-password:
    description: "The password to use to authenticate to the NPM repository"
    required: true
runs:
  using: "node16"
  main: "../lib/should-publish-package-action/index.js"
