name: "Assert version available"
description: "Asserts that the version in the package.json is available on the registry"
inputs:
  repository-url:
    description: "The URL of the repository to check"
    required: true
  repository-login:
    description: "The login to use to authenticate to the NPM repository"
    required: true
  repository-password:
    description: "The password to use to authenticate to the NPM repository"
    required: true
runs:
  using: "node16"
  main: "../lib/set-next-dev-version-action/index.js"
